baseURL = "https://blog.mutoulbj.com"
languageCode = "zh-cn"
title = "咏函"
theme = "cactus"

[params]
    description = "二流程序员，目前写代码为生。全栈工程师（啥都不精），近几年从事大数据相关工作。社恐，这儿是我表达自我的地方，若有缘到此，还能给各位带来些许收获，就有幸之至了。"
    mainSection = "posts"
    mainSectionTitle = "Blog"

    showAllPostsOnHomePage = false
    postsOnHomePage = 20

    DateFormat = "2006-01-02"
    rss = true
    showAllPostsArchive = true
    css = ["css/custom.css"]

    [params.comments]
      enabled = true

    [[params.social]]
      name = "twitter"
      link = "https://twitter.com/mutoulbj"

    [[params.social]]
      name = "github"
      link = "https://github.com/mutoulbj"

    [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[menu.main]]
      name = "Develop"
      url = "/dev"
      weight = 2

    [[menu.main]]
      name = "Life"
      url = "/life"
      weight = 3

    [[menu.main]]
      name = "Tags"
      url = "/tags"
      weight = 4

    [[menu.main]]
      name = "About"
      url = "/about"
      weight = 5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4