baseURL = "https://blog.mutoulbj.com"
languageCode = "zh-cn"
title = "咏函"
theme = "cactus"
copyright = "木头lbj"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4

[params]
  rss = true
  showAllPostsArchive = true

  # Home page settings
  description = "程序员，目前写码为生。全干工程师，关注AI、大数据、充电桩行业"
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 10
  tagsOverview = true

  DateFormat = "2006-01-02"
  # css = ["css/custom.css"]

  show_updated = true
  showReadTime = true

  MicrosoftClarity = true
  MicrosoftClarityCode = "jtrzett5ez"

  MicrosoftWebmaster = true
  MicrosoftWebmasterCode = "A280EB1107791FE3524B7875D547F0BC"

  [params.comments]
    enabled = true
    engine = "utterances" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "mutoulbj/blog-yonghan"
      label = "blog-yonghan-comment" # you can use however you want to label your name in your repo's issues
      theme = "preferred-color-scheme"
      issueTerm = "pathname"

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/mutoulbj"

  [[params.social]]
    name = "github"
    link = "https://github.com/mutoulbj"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4